package boundary;

import javax.swing.*;
import java.awt.*;

public class GruppiPanel extends JPanel {
    private JPanel panel1;
    private JPanel headerPanel;
    private JLabel labelTitolo;
    private JButton bottoneNuovoGruppo;
    private JPanel listaGruppiPanel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        headerPanel = new JPanel();
        headerPanel.setLayout(new BorderLayout(0, 0));
        panel1.add(headerPanel, BorderLayout.NORTH);
        labelTitolo = new JLabel();
        labelTitolo.setText("I miei gruppi");
        headerPanel.add(labelTitolo, BorderLayout.WEST);
        bottoneNuovoGruppo = new JButton();
        bottoneNuovoGruppo.setText("+ Nuovo gruppo");
        headerPanel.add(bottoneNuovoGruppo, BorderLayout.EAST);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, BorderLayout.CENTER);
        listaGruppiPanel = new JPanel();
        listaGruppiPanel.setLayout(new BorderLayout(0, 0));
        scrollPane1.setViewportView(listaGruppiPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
    private final control.MainController mainController;
    private final control.GruppoController gruppoController = new control.GruppoController();

    public GruppiPanel(control.MainController mainController) {
        this.mainController = mainController;

        setLayout(new java.awt.BorderLayout());
        add(panel1, java.awt.BorderLayout.CENTER);

        listaGruppiPanel.setLayout(new BoxLayout(listaGruppiPanel, BoxLayout.Y_AXIS));

        bottoneNuovoGruppo.addActionListener(e -> onNuovoGruppo());

        caricaGruppi();
    }

    public void caricaGruppi() {
        listaGruppiPanel.removeAll();

        try {
            java.util.List<entity.Gruppo> gruppi = gruppoController.getGruppiUtente(
                    mainController.getUtenteLoggato().getMatricola());

            if (gruppi.isEmpty()) {
                JLabel vuoto = new JLabel("Non fai ancora parte di nessun gruppo. Creane uno!");
                vuoto.setAlignmentX(Component.LEFT_ALIGNMENT);
                listaGruppiPanel.add(vuoto);
            } else {
                for (entity.Gruppo gruppo : gruppi) {
                    listaGruppiPanel.add(creaGruppoCard(gruppo));
                    listaGruppiPanel.add(Box.createVerticalStrut(10));
                }
            }

        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(this, "Errore nel caricamento dei gruppi");
            ex.printStackTrace();
        }

        listaGruppiPanel.revalidate();
        listaGruppiPanel.repaint();
    }

    private JPanel creaGruppoCard(entity.Gruppo gruppo) {
        JPanel card = new JPanel();
        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
        card.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(Color.LIGHT_GRAY),
                BorderFactory.createEmptyBorder(10, 15, 10, 15)));
        card.setAlignmentX(Component.LEFT_ALIGNMENT);
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 100));

        JLabel labelNome = new JLabel(gruppo.getNome());
        labelNome.setFont(labelNome.getFont().deriveFont(Font.BOLD, 15f));

        JLabel labelInfo = new JLabel(gruppo.getNumPartecipanti() + " partecipanti");
        labelInfo.setForeground(Color.GRAY);

        card.add(labelNome);
        card.add(labelInfo);

        card.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                onSelezionaGruppo(gruppo);
            }
        });
        card.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        return card;
    }

    private void onSelezionaGruppo(entity.Gruppo gruppo) {
        JOptionPane.showMessageDialog(this,
                "Apertura dettaglio gruppo: " + gruppo.getNome() + "\n(schermata in arrivo)",
                "In sviluppo", JOptionPane.INFORMATION_MESSAGE);
    }

    private void onNuovoGruppo() {
        NuovoGruppoDialog dialog = new NuovoGruppoDialog(
                (JFrame) SwingUtilities.getWindowAncestor(this),
                mainController.getUtenteLoggato().getMatricola());
        dialog.setVisible(true);

        if (dialog.isGruppoCreato()) {
            caricaGruppi(); // ricarica la lista dopo la creazione
        }
    }
}

