package boundary;

import javax.swing.*;
import java.awt.*;

public class GruppiPanel {
    private JPanel panel1;
    private JPanel headerPanel;
    private JLabel labelTitolo;
    private JButton bottoneNuovoGruppo;
    private JScrollPane scrollGruppi;
    private JPanel listaGruppiPanel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
        listaGruppiPanel.setLayout(new BoxLayout(listaGruppiPanel, BoxLayout.Y_AXIS));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        headerPanel = new JPanel();
        headerPanel.setLayout(new BorderLayout(0, 0));
        panel1.add(headerPanel, BorderLayout.NORTH);
        labelTitolo = new JLabel();
        labelTitolo.setText("I miei gruppi");
        headerPanel.add(labelTitolo, BorderLayout.WEST);
        bottoneNuovoGruppo = new JButton();
        bottoneNuovoGruppo.setText("+ Nuovo gruppo");
        headerPanel.add(bottoneNuovoGruppo, BorderLayout.EAST);
        scrollGruppi = new JScrollPane();
        panel1.add(scrollGruppi, BorderLayout.CENTER);
        listaGruppiPanel = new JPanel();
        listaGruppiPanel.setLayout(new BorderLayout(0, 0));
        scrollGruppi.setViewportView(listaGruppiPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
    public JPanel getRootPanel() {
        return panel1;
    }

    public void caricaGruppi(entity.Utente utenteLoggato, control.MainController mainController) {
        listaGruppiPanel.removeAll();
        try {
            control.GruppoController gruppoController = new control.GruppoController();
            java.util.List<entity.Gruppo> gruppi = gruppoController.getGruppiUtente(utenteLoggato.getMatricola());
            for (entity.Gruppo gruppo : gruppi) {
                boolean isProprietario = gruppo.getMatricolaCreatore().equals(utenteLoggato.getMatricola());
                GruppoCard card = new GruppoCard(gruppo, isProprietario, 0, 0.0,
                        () -> JOptionPane.showMessageDialog(panel1, "Apri gruppo: " + gruppo.getNome()));
                listaGruppiPanel.add(card.getRootPanel());
                listaGruppiPanel.add(Box.createVerticalStrut(8));
            }
        } catch (java.sql.SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(panel1, "Errore nel caricamento dei gruppi");
        }
        listaGruppiPanel.revalidate();
        listaGruppiPanel.repaint();
    }
}
