package boundary;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class GruppoCard {
    private JPanel panel1;
    private JPanel infoPanel;
    private JLabel labelNome;
    private JLabel labelRuolo;
    private JLabel labelStats;
    private JLabel labelSaldo;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(12, 16, 12, 16), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        infoPanel = new JPanel();
        infoPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(infoPanel, BorderLayout.WEST);
        labelNome = new JLabel();
        Font labelNomeFont = this.$$$getFont$$$(null, Font.BOLD, 14, labelNome.getFont());
        if (labelNomeFont != null) labelNome.setFont(labelNomeFont);
        labelNome.setText("Nome Gruppo");
        infoPanel.add(labelNome, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelRuolo = new JLabel();
        Font labelRuoloFont = this.$$$getFont$$$(null, -1, 11, labelRuolo.getFont());
        if (labelRuoloFont != null) labelRuolo.setFont(labelRuoloFont);
        labelRuolo.setForeground(new Color(-8224126));
        labelRuolo.setText("Proprietario");
        infoPanel.add(labelRuolo, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelStats = new JLabel();
        labelStats.setHorizontalAlignment(0);
        labelStats.setText("3 partecipanti · 12 spese");
        panel1.add(labelStats, BorderLayout.CENTER);
        labelSaldo = new JLabel();
        Font labelSaldoFont = this.$$$getFont$$$(null, Font.BOLD, 14, labelSaldo.getFont());
        if (labelSaldoFont != null) labelSaldo.setFont(labelSaldoFont);
        labelSaldo.setText("+45,00 €");
        panel1.add(labelSaldo, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
    public JComponent getRootPanel() {
        return panel1;
    }

    public GruppoCard(entity.Gruppo gruppo, boolean isProprietario, int numSpese, double saldoUtente, Runnable onClick) {

        labelNome.setText(gruppo.getNome());
        labelRuolo.setText(isProprietario ? "Proprietario" : " ");
        labelStats.setText(gruppo.getNumPartecipanti() + " partecipanti · " + numSpese + " spese");

        labelSaldo.setText(String.format("%+.2f €", saldoUtente));
        labelSaldo.setForeground(saldoUtente >= 0 ? new Color(0, 150, 0) : new Color(200, 0, 0));

        panel1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                onClick.run();
            }
        });
    }
}
