package boundary;

import control.MainController;
import entity.Utente;

import javax.swing.*;
import java.awt.*;

public class MainFrame extends JFrame {

    private JPanel panel1;
    private JPanel menuPanel;
    private JPanel contentPanel;
    private JLabel labelNomeUtente;
    private JLabel labelEmailUtente;
    private JButton bottoneGruppi;
    private JButton bottoneInviti;
    private JLabel labelBadgeInviti;
    private JButton bottoneLogout;

    private MainController mainController;

    public MainFrame(Utente utenteLoggato) {
        setTitle("UninaMoneySplit");
        setContentPane(panel1);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1000, 650);
        setLocationRelativeTo(null);

        this.mainController = new MainController(this, utenteLoggato);

        labelNomeUtente.setText(utenteLoggato.getNome() + " " + utenteLoggato.getCognome());
        labelEmailUtente.setText(utenteLoggato.getEmail());

        bottoneGruppi.addActionListener(e -> mainController.showPanel("gruppi"));
        bottoneInviti.addActionListener(e -> mainController.showPanel("inviti"));
        bottoneLogout.addActionListener(e -> onLogout());

        mainController.showPanel("gruppi");
    }

    public void setContentPanel(JPanel nuovoPanel) {
        contentPanel.removeAll();
        contentPanel.setLayout(new BorderLayout());
        contentPanel.add(nuovoPanel, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
    }

    public void aggiornaBadgeInviti(int numeroInviti) {
        if (numeroInviti > 0) {
            labelBadgeInviti.setText(String.valueOf(numeroInviti));
            labelBadgeInviti.setVisible(true);
        } else {
            labelBadgeInviti.setVisible(false);
        }
    }

    private void onLogout() {
        dispose();
        SwingUtilities.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        menuPanel = new JPanel();
        menuPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 1, new Insets(0, 0, 0, 0), -1, -1));
        menuPanel.setMinimumSize(new Dimension(200, -1));
        panel1.add(menuPanel, BorderLayout.WEST);
        labelNomeUtente = new JLabel();
        labelNomeUtente.setText("Nome Utente");
        menuPanel.add(labelNomeUtente, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelEmailUtente = new JLabel();
        labelEmailUtente.setText("email@unina.it");
        menuPanel.add(labelEmailUtente, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bottoneGruppi = new JButton();
        bottoneGruppi.setText("I miei gruppi");
        menuPanel.add(bottoneGruppi, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bottoneInviti = new JButton();
        bottoneInviti.setText("Inviti");
        menuPanel.add(bottoneInviti, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelBadgeInviti = new JLabel();
        labelBadgeInviti.setText("0");
        menuPanel.add(labelBadgeInviti, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bottoneLogout = new JButton();
        bottoneLogout.setText("Logout");
        menuPanel.add(bottoneLogout, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        contentPanel = new JPanel();
        contentPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(contentPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}